name: Release OVF
on:
  workflow_dispatch:
  push: 
    branches:
      - 'master'
      - 'releases/**'

env:
  PRODUCT_VERSION: "latest-rc"

jobs:
  packer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v2.0.0
        
      - name: Run build script
        run: "./build.sh"
        
      #- name: Cache
      #  uses: actions/cache@v1.2.1
      #  with:
      #    path: $HOME/.config/packer
        
      - name: Create a Release
        uses: elgohr/Github-Release-Action@main
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: ${{ github.sha }}
