---
name: Release OVF

permissions:
  contents: write
  pull-requests: write
  discussions: write
  
on:
  workflow_dispatch: null
  push:
    branches:
      - master
      - releases/**

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2.2.0
        with:
          platforms: x86_64
      - uses: hashicorp/setup-packer@v2.0.0
      - uses: open-policy-agent/setup-opa@v2
      
      - name: Check file existence
        id: check_policies
        uses: andstor/file-existence-action@v1
        with:
          files: "policy/packer.rego"

      - name: Validate conf with OPA
        if: steps.check_files.outputs.files_exists == 'true'
        run: opa test -v policy/packer.rego alpine-docker-host-x86_64.json 

      - name: Run build script
        run: ./build.sh

      - name: Create a Release
        env:
           GITHUB_USER: ${{ secrets.GITHUB_USER }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GITHUB_REPOSITORY: ${{ vars.REPOSITORY_VAR }}
        run: |
           hub release create -m "${{ github.sha }}" "$(date +%Y%m%d%H%M%S)"
...
