---
name: Release OVF
on:
  workflow_dispatch: null
  push:
    branches:
      - master
      - releases/**
jobs:
  packer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      discussions: write
    name: Run Packer
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-packer@v2.0.0
      - uses: geertvdc/setup-hub@v1.0.0
      - name: Run build script
        run: ./build.sh
      - name: Create a Release
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ vars.REPOSITORY_VAR }}
          run: |
            hub release create -m "${{ github.sha }}" "$(date +%Y%m%d%H%M%S)"
...
